# Call Density Estimatation of Burrowing Owls

Inspired by:
https://github.com/google-research/perch/blob/75fdf0f6ae4055e68dd5037b29a872fc5edcf3f3/chirp/inference/call_density.py#L203

In [1]:
import pandas as pd

df = pd.read_csv("results/all_model_redictions_96545a6b81b24794962d464e8fcbdc1d.csv")

In [2]:
df.sort_values("alarm", ascending=False).head(20)

,Unnamed: 0,file_path,offset,confidence,pred_label,cluck,coocoo,twitter,alarm,chick_begging
94419,94419,/mnt/restorage/Audiomoth/Raw sound files/2024/...,24060,1.0,alarm,-22.402452,-22.912792,-25.546251,20.841814,-22.940740
264377,264377,/mnt/restorage/Audiomoth/Raw sound files/2024/...,15534,1.0,alarm,-23.803892,-22.825657,-27.006813,20.311157,-22.166344
541140,541140,/mnt/restorage/Audiomoth/Raw sound files/2024/...,1119,1.0,alarm,-25.184970,-26.255228,-29.697628,20.299944,-26.164640
452653,452653,/mnt/restorage/Audiomoth/Raw sound files/2024/...,61962,1.0,alarm,-21.331518,-23.090994,-26.027687,20.227350,-19.279821
119304,119304,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12315,1.0,alarm,-23.452198,-28.016869,-28.174654,19.819195,-26.273191
319247,319247,/mnt/restorage/Audiomoth/Raw sound files/2024/...,7344,1.0,alarm,-23.386164,-22.720860,-24.071678,19.668413,-17.495047
229054,229054,/mnt/restorage/Audiomoth/Raw sound files/2024/...,15255,1.0,alarm,-21.169392,-26.392405,-25.934864,19.562904,-23.121283
352330,352330,/mnt/restorage/Audiomoth/Raw sound files/2024/...,20193,1.0,alarm,-20.541220,-25.700777,-29.702793,19.557253,-24.470812
170601,170601,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12696,1.0,alarm,-20.716698,-21.405918,-23.731678,19.521215,-20.090147
485656,485656,/mnt/restorage/Audiomoth/Raw sound files/2024/...,7461,1.0,alarm,-23.593960,-24.920948,-26.808083,19.456106,-23.523579
263364,263364,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12495,1.0,alarm,-22.458614,-22.588552,-26.864017,19.248663,-22.837055
497751,497751,/mnt/restorage/Audiomoth/Raw sound files/2024/...,24459,1.0,alarm,-21.215244,-27.401781,-28.583170,19.219074,-25.051336
1343725,1343725,/mnt/restorage/Audiomoth/Raw sound files/2024/...,2028,1.0,alarm,-25.389788,-23.040852,-26.000677,19.212631,-20.353563
203919,203919,/mnt/restorage/Audiomoth/Raw sound files/2024/...,6960,1.0,alarm,-23.955410,-24.534792,-24.943047,19.143570,-18.985966
447948,447948,/mnt/restorage/Audiomoth/Raw sound files/2024/...,47847,1.0,alarm,-18.956785,-26.244870,-28.957003,18.997728,-25.885422
274848,274848,/mnt/restorage/Audiomoth/Raw sound files/2024/...,46947,1.0,alarm,-21.422125,-24.853804,-27.085964,18.969100,-23.310913
542203,542203,/mnt/restorage/Audiomoth/Raw sound files/2024/...,4308,1.0,alarm,-21.690222,-27.700727,-32.240875,18.961002,-26.760513
365543,365543,/mnt/restorage/Audiomoth/Raw sound files/2024/...,59832,1.0,alarm,-24.129976,-24.760447,-27.803371,18.859518,-25.263254
492776,492776,/mnt/restorage/Audiomoth/Raw sound files/2024/...,9534,1.0,alarm,-21.684350,-23.942354,-25.668602,18.851430,-23.828362
78257,78257,/mnt/restorage/Audiomoth/Raw sound files/2024/...,61971,1.0,alarm,-24.619108,-24.942354,-28.662867,18.838255,-23.987240

In [3]:
to_verify_examples = df.sort_values("alarm", ascending=False).head(20)
to_verify_examples

,Unnamed: 0,file_path,offset,confidence,pred_label,cluck,coocoo,twitter,alarm,chick_begging
94419,94419,/mnt/restorage/Audiomoth/Raw sound files/2024/...,24060,1.0,alarm,-22.402452,-22.912792,-25.546251,20.841814,-22.940740
264377,264377,/mnt/restorage/Audiomoth/Raw sound files/2024/...,15534,1.0,alarm,-23.803892,-22.825657,-27.006813,20.311157,-22.166344
541140,541140,/mnt/restorage/Audiomoth/Raw sound files/2024/...,1119,1.0,alarm,-25.184970,-26.255228,-29.697628,20.299944,-26.164640
452653,452653,/mnt/restorage/Audiomoth/Raw sound files/2024/...,61962,1.0,alarm,-21.331518,-23.090994,-26.027687,20.227350,-19.279821
119304,119304,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12315,1.0,alarm,-23.452198,-28.016869,-28.174654,19.819195,-26.273191
319247,319247,/mnt/restorage/Audiomoth/Raw sound files/2024/...,7344,1.0,alarm,-23.386164,-22.720860,-24.071678,19.668413,-17.495047
229054,229054,/mnt/restorage/Audiomoth/Raw sound files/2024/...,15255,1.0,alarm,-21.169392,-26.392405,-25.934864,19.562904,-23.121283
352330,352330,/mnt/restorage/Audiomoth/Raw sound files/2024/...,20193,1.0,alarm,-20.541220,-25.700777,-29.702793,19.557253,-24.470812
170601,170601,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12696,1.0,alarm,-20.716698,-21.405918,-23.731678,19.521215,-20.090147
485656,485656,/mnt/restorage/Audiomoth/Raw sound files/2024/...,7461,1.0,alarm,-23.593960,-24.920948,-26.808083,19.456106,-23.523579
263364,263364,/mnt/restorage/Audiomoth/Raw sound files/2024/...,12495,1.0,alarm,-22.458614,-22.588552,-26.864017,19.248663,-22.837055
497751,497751,/mnt/restorage/Audiomoth/Raw sound files/2024/...,24459,1.0,alarm,-21.215244,-27.401781,-28.583170,19.219074,-25.051336
1343725,1343725,/mnt/restorage/Audiomoth/Raw sound files/2024/...,2028,1.0,alarm,-25.389788,-23.040852,-26.000677,19.212631,-20.353563
203919,203919,/mnt/restorage/Audiomoth/Raw sound files/2024/...,6960,1.0,alarm,-23.955410,-24.534792,-24.943047,19.143570,-18.985966
447948,447948,/mnt/restorage/Audiomoth/Raw sound files/2024/...,47847,1.0,alarm,-18.956785,-26.244870,-28.957003,18.997728,-25.885422
274848,274848,/mnt/restorage/Audiomoth/Raw sound files/2024/...,46947,1.0,alarm,-21.422125,-24.853804,-27.085964,18.969100,-23.310913
542203,542203,/mnt/restorage/Audiomoth/Raw sound files/2024/...,4308,1.0,alarm,-21.690222,-27.700727,-32.240875,18.961002,-26.760513
365543,365543,/mnt/restorage/Audiomoth/Raw sound files/2024/...,59832,1.0,alarm,-24.129976,-24.760447,-27.803371,18.859518,-25.263254
492776,492776,/mnt/restorage/Audiomoth/Raw sound files/2024/...,9534,1.0,alarm,-21.684350,-23.942354,-25.668602,18.851430,-23.828362
78257,78257,/mnt/restorage/Audiomoth/Raw sound files/2024/...,61971,1.0,alarm,-24.619108,-24.942354,-28.662867,18.838255,-23.987240

In [4]:
# 0 is true, 1 is false, 2 is unsure
verified = []

In [7]:
import librosa
import numpy as np
from IPython.display import Audio
from IPython.display import clear_output

for i, row in to_verify_examples.iterrows():
    if i < len(verified):
        continue
    y, sr = librosa.load(path=row["file_path"].replace(
    "/mnt/restorage/Audiomoth/Raw sound files/2024/RGCB", "data/2024_RGCB"
    ), offset=row["offset"], duration=3)
    display(Audio(data=y, rate=sr))
    # fig.savefig(f"data/burrowing_owl_dataset/img/{file_meta["path"][-20:]}_{file_meta["offset"]}_spec.jpg")


    print(
        i, row["file_path"],
        "\t", row["offset"],
        )
    verified.append(int(input("Correct Prediction of Alarm Call? 0,1,2")))
    clear_output(wait=True)

78257 /mnt/restorage/Audiomoth/Raw sound files/2024/RGCB/AB10/B032/20240524-0607_032_continuous/20240526_000002.WAV 	 61971

In [8]:
to_verify_examples["verifications"] = verified
to_verify_examples["verifications"].value_counts()

verifications
0    20
Name: count, dtype: int64

In [ ]:
'/mnt/restorage/Audiomoth/Raw sound files/2024/RGCB/AB10/B032/20240524-0607_032_continuous/20240527_000002.WAV'

'data/2024_RGCB/AB10/B032/20240524-0607_032_continuous/20240527_000002.WAV'

In [15]:
best_df = df[(df["confidence"] > 0.9) & (df["pred_label"] != "no_buow")]
best_df

,Unnamed: 0,file_path,offset,confidence,pred_label,cluck,coocoo,twitter,alarm,chick_begging
113,113,/mnt/restorage/Audiomoth/Raw sound files/2024/...,339,0.967754,alarm,-8.170012,-13.413010,-10.759006,1.377641,-8.898106
213,213,/mnt/restorage/Audiomoth/Raw sound files/2024/...,639,1.000000,coocoo,-10.910990,9.119572,-10.636287,-8.673664,-12.479684
338,338,/mnt/restorage/Audiomoth/Raw sound files/2024/...,1014,0.999174,cluck,3.389108,-11.462462,-9.719512,-7.483607,-11.097157
936,936,/mnt/restorage/Audiomoth/Raw sound files/2024/...,2808,1.000000,coocoo,-10.838291,9.931961,-11.080215,-10.234681,-11.922439
937,937,/mnt/restorage/Audiomoth/Raw sound files/2024/...,2811,1.000000,cluck,8.061478,-11.183188,-9.406314,-8.867446,-11.057000
...,...,...,...,...,...,...,...,...,...,...
2717522,2717522,/mnt/restorage/Audiomoth/Raw sound files/2024/...,19086,0.936049,alarm,-12.034642,-15.206326,-14.176944,1.633450,-9.495346
2717529,2717529,/mnt/restorage/Audiomoth/Raw sound files/2024/...,19107,0.998127,alarm,-6.970337,-9.188694,-9.514184,3.007450,-3.799388
2717542,2717542,/mnt/restorage/Audiomoth/Raw sound files/2024/...,19146,0.999993,alarm,-10.027398,-13.577842,-14.333464,5.897042,-10.503337
2717543,2717543,/mnt/restorage/Audiomoth/Raw sound files/2024/...,19149,0.987917,alarm,-11.593224,-13.846678,-14.586676,2.381190,-7.628112
2717548,2717548,/mnt/restorage/Audiomoth/Raw sound files/2024/...,19164,0.976367,alarm,-10.067089,-12.619599,-12.024328,2.132289,-7.145093

In [29]:
import os
file_path = '/mnt/restorage/Audiomoth/Raw sound files/2024/RGCB/AB10/B032/20240524-0607_032_continuous/20240527_000002.WAV'

for file_path in set(best_df["file_path"]):
    test = best_df[best_df["file_path"] == file_path]
    test["Begin Time (s)"] = test["offset"]
    test["End Time (s)"] = test["offset"] + 3
    test["Selection"] = 1
    test["Low Freq (Hz)"] = 0
    test['High Freq (Hz)'] = 16_000
    os.makedirs(os.path.dirname(f"results/buow_predictions{file_path}"), exist_ok=True)
    test.to_csv(f"results/buow_predictions{file_path}".replace("WAV", "txt"), sep="\t")

/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Begin Time (s)"] = test["offset"]
/tmp/ipykernel_536914/1253521940.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["End Time (s)"] = test["offset"] + 3
/tmp/ipykernel_536914/1253521940.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Selection"] = 1
/tmp/ipykernel_536914/1253521940.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Low Freq (Hz)"] = 0
/tmp/ipykernel_536914/1253521940.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['High Freq (Hz)'] = 16_000
/tmp/ipykernel_536914/1253521940.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

In [ ]:
def to_raven(df, file_col, start_time_col="offset", duration=None, end_time_col=None):
    # Standard Raven Pro header
    header = [
        'Selection', 'View', 'Channel', 'Begin Time (s)', 'End Time (s)', 'Low Freq (Hz)', 'High Freq (Hz)'
        # 'Low Freq (Hz)', 'High Freq (Hz)', 'Delta Time (s)', 'Delta Freq (Hz)',
        'Label'
    ]


    df.groupby(file_col).apply


    # Add a selection number if missing
    if 'Selection' not in df.columns:
        df.insert(0, 'Selection', range(1, len(df) + 1))
    
    # Optional fields
    df['View'] = df.get('View', 'Spectrogram 1')
    df['Channel'] = df.get('Channel', 1)
    df['Delta Time (s)'] = df['End Time (s)'] - df['Begin Time (s)']
    df['Delta Freq (Hz)'] = df['High Freq (Hz)'] - df['Low Freq (Hz)']
    df['Avg Power (dB)'] = df.get('Avg Power (dB)', '')
    
    # Reorder columns
    df_out = df.reindex(columns=header + [c for c in df.columns if c not in header])
    
    # Write to tab-delimited file
    df_out.to_csv(output_path, sep='\t', index=False)
    print(f"✅ Raven selection table saved to {output_path}")

# Example usage
if __name__ == "__main__":
    data = {
        'Begin Time (s)': [0.25, 1.2, 3.7],
        'End Time (s)': [0.75, 1.8, 4.1],
        'Low Freq (Hz)': [1000, 1500, 1200],
        'High Freq (Hz)': [5000, 5500, 4800]
    }
    df = pd.DataFrame(data)
    dataframe_to_raven(df, "raven_selection_table.txt")